import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const myFont = localFont({
  src:'NanumBrush.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'team 29',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
