/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oyZnkgaLkYN
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export default function Booklist({ setShowBooklist }) {
  return (
    <div className="min-h-screen min-w-full bg-[#F3F4F6]">
      <header className="flex justify-between items-center bg-white p-4 shadow-md">
        <Link href="#">
          <span className="ml-2 font-semibold text-lg">북리스트</span>
        </Link>
        <Link href="#">
          <span className="ml-2 font-semibold text-lg">5세 추천</span>
        </Link>
        <Link href="#">
          <span className="ml-2 font-semibold text-lg">6세 추천</span>
        </Link>
        <Link href="#">
          <span className="ml-2 font-semibold text-lg">마이페이지</span>
        </Link>

        <Button variant="outline" onClick={() => setShowBooklist(false)}>로그아웃</Button>
      </header>
      <main className="p-4">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">

          <Card>
            <Link href="/list"> 
            {/* 아직 이 링크는 예시로 걸어논거고 연결되는 주소가 없음 */}
              <CardHeader>
                <Avatar className="w-12 h-12" src="/placeholder.svg?height=100&width=100" />
                <h2 className="ml-4 text-lg font-semibold">Flight Details</h2>
              </CardHeader>
              <CardContent>
                <p className="text-sm">
                  Flight number: <span className="font-medium">FL001</span>
                </p>
                <p className="text-sm">
                  Departure: <span className="font-medium">New York</span>
                </p>
                <p className="text-sm">
                  Destination: <span className="font-medium">Los Angeles</span>
                </p>
                <p className="text-sm">
                  Departure Time: <span className="font-medium">10:00 AM</span>
                </p>
              </CardContent>
            </Link>
          </Card>

          <Card>
            <CardHeader>
              <Avatar className="w-12 h-12" src="/placeholder.svg?height=100&width=100" />
              <h2 className="ml-4 text-lg font-semibold">Flight Status</h2>
            </CardHeader>
            <CardContent>
              <p className="text-sm">
                Status: <Badge variant="success">On Time</Badge>
              </p>
              <p className="text-sm">
                Gate: <span className="font-medium">B12</span>
              </p>
              <p className="text-sm">
                Seat: <span className="font-medium">14A</span>
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Avatar className="w-12 h-12" src="/placeholder.svg?height=100&width=100" />
              <h2 className="ml-4 text-lg font-semibold">Flight Status</h2>
            </CardHeader>
            <CardContent>
              <p className="text-sm">
                Status: <Badge variant="success">On Time</Badge>
              </p>
              <p className="text-sm">
                Gate: <span className="font-medium">B12</span>
              </p>
              <p className="text-sm">
                Seat: <span className="font-medium">14A</span>
              </p>
            </CardContent>
          </Card>


          <Card>
            <CardHeader>
              <Avatar className="w-12 h-12" src="/placeholder.svg?height=100&width=100" />
              <h2 className="ml-4 text-lg font-semibold">Flight Status</h2>
            </CardHeader>
            <CardContent>
              <p className="text-sm">
                Status: <Badge variant="success">On Time</Badge>
              </p>
              <p className="text-sm">
                Gate: <span className="font-medium">B12</span>
              </p>
              <p className="text-sm">
                Seat: <span className="font-medium">14A</span>
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <Avatar className="w-12 h-12" src="/placeholder.svg?height=100&width=100" />
              <h2 className="ml-4 text-lg font-semibold">Passenger Information</h2>
            </CardHeader>
            <CardContent>
              <p className="text-sm">
                Name: <span className="font-medium">John Doe</span>
              </p>
              <p className="text-sm">
                Passport: <span className="font-medium">123456789</span>
              </p>
              <p className="text-sm">
                Frequent Flyer: <Badge variant="secondary">Platinum</Badge>
              </p>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function PlaneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  )
}
