/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hJ83567i6PK
 */
import { Skeleton } from "@/components/ui/skeleton"

export function loadingPage() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100">
      <div className="flex flex-col items-center space-y-4">
        <LoaderIcon className="w-12 h-12 animate-spin" />
        <h1 className="text-2xl font-semibold">Loading...</h1>
        <div className="w-full max-w-md p-4">
          <Skeleton className="h-2 w-full rounded" />
        </div>
      </div>
    </div>
  )
}


function LoaderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="6" />
      <line x1="12" x2="12" y1="18" y2="22" />
      <line x1="4.93" x2="7.76" y1="4.93" y2="7.76" />
      <line x1="16.24" x2="19.07" y1="16.24" y2="19.07" />
      <line x1="2" x2="6" y1="12" y2="12" />
      <line x1="18" x2="22" y1="12" y2="12" />
      <line x1="4.93" x2="7.76" y1="19.07" y2="16.24" />
      <line x1="16.24" x2="19.07" y1="7.76" y2="4.93" />
    </svg>
  )
}
